MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
KAFKA_DIR="${MY_DIR}/kafka-1.1.0"
BROKER_CONFIG_DIR="${MY_DIR}/configs/kafka"
ZOO_CONFIG_DIR="${MY_DIR}/configs/zookeeper"
CONNECT_CONFIG_DIR="${MY_DIR}/configs/connect"